"""new fields in user table

Revision ID: 053cd06e5a93
Revises: 457fdd45f14a
Create Date: 2025-01-23 21:49:05.167962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '053cd06e5a93'
down_revision = '457fdd45f14a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
